//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.1
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientPOI.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso con establecimiento inflexible de tipos, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o vuelva a generar su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClientPOI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso con establecimiento inflexible de tipos.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        internal static System.Drawing.Bitmap triste
        {
            get
            {
                object obj = ResourceManager.GetObject("triste", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        

        }

        internal static System.Drawing.Bitmap aliviado
        {
            get
            {
                object obj = ResourceManager.GetObject("aliviado", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }


        }

        internal static System.Drawing.Bitmap asco
        {
            get
            {
                object obj = ResourceManager.GetObject("asco", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }


        }

        internal static System.Drawing.Bitmap beso
        {
            get
            {
                object obj = ResourceManager.GetObject("beso", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }


        }

        internal static System.Drawing.Bitmap desanimado
        {
            get
            {
                object obj = ResourceManager.GetObject("desanimado", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }


        }

        internal static System.Drawing.Bitmap fastidiado
        {
            get
            {
                object obj = ResourceManager.GetObject("fastidiado", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }


        }

        internal static System.Drawing.Bitmap enamorado
        {
            get
            {
                object obj = ResourceManager.GetObject("enamorado", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }


        }

        internal static System.Drawing.Bitmap feliz
        {
            get
            {
                object obj = ResourceManager.GetObject("feliz", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
}

        internal static System.Drawing.Bitmap jijitl
        {
            get
            {
                object obj = ResourceManager.GetObject("jijitl", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }


        }

        internal static System.Drawing.Bitmap guiño
        {
            get
            {
                object obj = ResourceManager.GetObject("guiño", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }


        }


        internal static System.Drawing.Bitmap lagrima
        {
            get
            {
                object obj = ResourceManager.GetObject("lagrima", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }


        }

        internal static System.Drawing.Bitmap MuyFeliz
        {
            get
            {
                object obj = ResourceManager.GetObject("MuyFeliz", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }


        }

        internal static System.Drawing.Bitmap pícaro
        {
            get
            {
                object obj = ResourceManager.GetObject("pícaro", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }


        }

        internal static System.Drawing.Bitmap lengua
        {
            get
            {
                object obj = ResourceManager.GetObject("lengua", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }


        }


        internal static System.Drawing.Bitmap sonrisa
        {
            get
            {
                object obj = ResourceManager.GetObject("sonrisa", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }


        }


        internal static System.Drawing.Bitmap sonrojado
        {
            get
            {
                object obj = ResourceManager.GetObject("sonrojado", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }


        }

        internal static System.IO.UnmanagedMemoryStream zumbix
        {
            get
            {
                return ResourceManager.GetStream("zumbix", resourceCulture);
            }
        }






    }



}
